apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mutate-webhook
  namespace: test
  labels:
    app: test-mutate-webhook
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-mutate-webhook
  template:
    metadata:
      labels:
        app: test-mutate-webhook
    spec:
      serviceAccountName: test-mutate-webhook
      containers:
        - name: server
          args:
            - --v=5
            - --namespace=test
            - --servicename=test-mutate-webhook
            - --namespacelabel=test-webhook
            - --serviceselectorkey=app
            - --serviceselectorvalue=test-mutate-webhook
            - --webhookconfigname=test-admission-mutate
            - --webhookname=test-mutate-webhook.noorganization.io
          image: ttl.sh/admission-prac
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18443
              name: admission-api